name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
      - name: Containers
        run : |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag docker.io/eugeneivanov/stress:latest
            --output "type=image,push=true" \
             -f Dockerfile .
             
